if type brew &>/dev/null
then
  source $(brew --prefix)/share/antigen/antigen.zsh
  export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
else
  source ~/.antigen.zsh
fi

# Some tips from c't
autoload -Uz promptinit
promptinit
prompt adam2
## Auto complete
autoload -Uz compinit
compinit

## Auto Spell Correct
setopt correct

HISTSIZE=99999
SAVEHIST=99999
export HISTTIMEFORMAT="%y-%m-%d %T "
HISTFILE=~/.zsh_history
setopt histignorespace
setopt hist_ignore_all_dups
setopt append_history
setopt share_history

# Antigen plugins
source ~/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# More plugins
antigen bundle git
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle colored-man-pages
antigen bundle iterm2

# Load the theme.
antigen theme robbyrussell

if type brew &>/dev/null
then
  antigen bundle thefuck
fi

antigen apply

# Aliases
alias ll='ls -lah'
# Tail last 50 lines of docker logs
alias dtail='docker logs -tf --tail='50' '

# Shorthand, customise docker-compose.yaml location as needed
alias dcp='docker-compose -f ~/docker-compose.yaml '
